[MID-37] adapt header footer to mobile
keenethics/mayak pull request #27
Opened 2024-02-12 07:33 UTC by IvanKoshan

this is a pr for this task https://trello.com/c/kpQr5uMu/37

live demo:  https://ivan-koshans-mayak.vercel.app/test/mobile

2024-02-13 11:57 UTC, alex-popov-tech approved these changes

2024-02-13 11:57 UTC, alex-popov-tech commented on src/app/_hooks/index.js
> +export { useBodyScrollLock } from './useBodyScrollLock';
🟢 `export *` a bit shorter

2024-02-16 10:03 UTC, yataras requested changes

2024-02-16 10:03 UTC, yataras commented on src/app/_hooks/useBodyScrollLock.js
> +  }
This part is not good. Your ideas is clear, you wan't to make `axis` be required. But will be checked only on execution (kudos to TS). You can add a default value to `axis` instead.

2024-02-16 10:03 UTC, yataras commented on src/app/_hooks/useBodyScrollLock.js
> +  });
Don't forget to add dependencies `[locked, axis]` to avoid unnecessary runs.

2024-02-16 10:03 UTC, yataras commented on src/app/_hooks/useBodyScrollLock.js
> +    return () => {
@IvanKoshan Good job!

2024-02-16 10:03 UTC, yataras commented on src/app/_components/Header.js
> +  }
It is better to wrap this function with `useCallback` hook to avoid unnecessary re-rendering, since it is passed to child components.

2024-02-16 12:45 UTC, IvanKoshan commented on src/app/_hooks/useBodyScrollLock.js
> +  }
Added default value

2024-02-16 12:45 UTC, IvanKoshan commented on src/app/_hooks/useBodyScrollLock.js
> +  });
done

2024-02-16 12:45 UTC, IvanKoshan commented on src/app/_components/Header.js
> +  }
done it

2024-02-16 12:45 UTC, IvanKoshan commented on src/app/_hooks/useBodyScrollLock.js
> +    return () => {
@yataras Fixed all of the issues presented

2024-02-16 13:22 UTC, yataras commented on src/app/_hooks/useBodyScrollLock.js
> +    return () => {
@IvanKoshan Thanks!

2024-02-16 13:22 UTC, yataras approved these changes

2024-02-16 14:15 UTC, Mykhailo-Pasternak approved these changes

2024-02-16 14:15 UTC, Mykhailo-Pasternak commented on src/app/_components/Header.js
> +            'absolute left-[100dvw] top-0 flex h-dvh w-dvw flex-col bg-other-black transition-all duration-300 lg:hidden',
🟢 you used: "dvw," "dvh" 🥇 👍

2024-02-20 18:03 UTC, merged