[MID-34] add not found page
keenethics/mayak pull request #32
Opened 2024-02-14 18:03 UTC by Mykhailo-Pasternak

How to check it:
1) Go to DEMONSTRATION and click on the link: 
https://mayak-ft06zn7uj-pozakhmarnyi.vercel.app/not-found

2) DONE

ticket: https://trello.com/c/GS4RQ6nH/34-%D0%B4%D0%BE%D0%B4%D0%B0%D1%82%D0%B8-%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%B8%D1%82%D0%B8-not-found-404-%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D0%BA%D1%83

2024-02-15 11:22 UTC, alex-popov-tech approved these changes

2024-02-15 11:58 UTC, IvanKoshan commented on public/assets/icons/notFound.png
🔴There are some benefits to using SVGs rather than PNGs. Here in particular it allows for better scaling. Also it can be more lightweight. Since this image can be exported as SVG in figma, you should export it as SVG rather than PNG.

2024-02-15 12:06 UTC, IvanKoshan requested changes

2024-02-15 12:06 UTC, IvanKoshan commented on src/app/not-found.js
> +const NotFoundPage = () => (
🔴Please follow the export and component declaration conventions established.
Use the following way of exporting
```js
export default function NotFoundPage() {
   // ....
}
```

2024-02-15 14:44 UTC, Mykhailo-Pasternak commented on public/assets/icons/notFound.png
@IvanKoshan **The first thing I did was using SVG.** 
But as an SVG, it was not displayed, something is wrong with it :( 
That's why I had to use PNG. To optimize the weight, I used png (https://squoosh.app/) - but it was already of optimal quality and, accordingly, the weight.

  _You can try it yourself._

2024-02-15 19:19 UTC, IvanKoshan approved these changes

2024-02-16 10:48 UTC, steven-tailor commented on src/app/not-found.js
> +          Not found
It looks a bit messy that part of the page is in English and other is in Ukrainian

2024-02-16 10:48 UTC, steven-tailor commented on src/app/not-found.js
> +          priority="true"
```suggestion
          priority
```

2024-02-16 10:59 UTC, steven-tailor approved these changes

2024-02-16 13:43 UTC, merged